<?php

namespace AppBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($pub){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM AppBundle:Publication p
                WHERE p.titre LIKE :pub'
            )
            ->setParameter('pub', '%'.$pub.'%')
            ->getResult();
    }



}
